### ISSUE TITLE
Optional single database bootstrap

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-features-api-cdk#13]
## Description

The current [WFS staging features api](https://github.com/NASA-IMPACT/veda-features-api/blob/main/terraform/veda-wfs3/rds.tf) has a single database and user while veda-features-api-cdk sets up two databases; one admin and the other "new user" that contains the data. This causes an issue when creating an rds with a snapshot from the WFS features api. The databases and users of the snapshot and veda-features-api-cdk rds bootstrap do not align so the features API is not able to see the snapshot data.

We will need to create an optional switch that creates a single database and user so features api will be able to work with a snapshot from wfs features api.

## Acceptance Criteria

- [x] Optional single database and user when bootstrapping rds

**Comment by ividito** [comment]
This ended up not needing changes to the construct, there was a config mismatch between the manually-created users and permissions on the snapshot, and the setting we were bootstrapping. Setting `VEDA_FEATURES_DB_DBNAME=veda` seems to have created a working catalog: https://staging.openveda.cloud/smce/api/features/
